### PR TITLE
Logentries.com reporter

### PR DESCRIPTION
**Pull request by seamusc**
A simple reporter to send metrics to logentries.com as key/value pairs.
Requires the log token for the log to send metrics to.

### CODE REVIEW

**Comment by pstadler** [comment]
Thanks for your PR.

Please adopt this reporter to be similar to https://github.com/pstadler/metrics.sh/blob/master/reporters/stathat.sh
- Add a `start()` function to check whether the token exists.
- Add a `docs()` function
- Don't define an empty value for the token
- Please rename the reporter to `logentries.com.sh`, it's too general in this case

**Comment by seamusc** [comment]
@pstadler changes applied. How's this looking?

**Comment by pstadler** [comment]
Thanks man. Could you please rename `LOGTOKEN` to `LOGENTRIES_TOKEN`. That would be all then. 👍

**Comment by pstadler** [comment]
Seamus,
I'm very sorry that this wasn't merged until now, as this got somehow lost in my inbox :-(
Merging and renaming the reporter to `logentries_com.sh` right away.

**Pull request merged**
